version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    env_file: ./.env
    networks:
      - container_link
    volumes:
      - ./:/app
    tty: true
    ports:
      - "18000:18000"
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "1"
networks:
  default:
    external: true
  container_link:
    name: go-rest.docker.internal